### ISSUE TITLE
Failed to create robot simulation interface loader

### ISSUE THREAD

**Issue by kperez009** [Ericsson/robot_hw_sim_latency#2]
We tried using this plugin to add a communication latency between Gazebo and ros-control, but we had the following error while trying to run the roslaunch file:

[FATAL] [1522765703.321669592, 0.167000000]: Failed to create robot simulation interface loader: According to the loaded plugin descriptions the class robot_hw_sim_latency/RobotHWSimLatency with base class type gazebo_ros_control::RobotHWSim does not exist. Declared types are  gazebo_ros_control/DefaultRobotHWSim

We have modified the urdf and added the rosparams as detailed in the description but it doesn't seem to work. 

Any help would be appreciated.

**Comment by nano-meter** [comment]
Did you source the proper workspace (the one containing robot_hw_sim_latency folder)? The problem is  ros can't find the robot_hw_sim_latency/RobotHWSimLatency plugin which was declared in: https://github.com/Ericsson/robot_hw_sim_latency/blob/master/robot_hw_sim_latency/robot_hw_sim_plugins.xml

You can use a command to print out available plugins: http://wiki.ros.org/pluginlib#pluginlib.2BAC8-pluginlib_groovy.Querying_ROS_Package_System_For_Available_Plugins

**Comment by kperez009** [comment]
Thanks for your quick reply, nano-meter. 
This morning everything worked perfectly without doing anything, I don't know what happend.
Thank you again and sorry for the inconvinience.
